### ISSUE TITLE
Listing saved connections?

### ISSUE THREAD

**Issue by zzzdeb** [firecat53/networkmanager-dmenu#72]
Is there a reason not to list saved connections.
Use case is for me at least very common.
For examble, I open my phone hotspot. Laptop always delays to show. But I know it is now open. I force it to connect and it always works with nm-applet. But for now, since nm-dmenu doesnt list it, I cant do it and have to reach to my mouse.

**Comment by firecat53** [comment]
I've chosen to only list available connections instead of listing all connections. There is the 'Rescan Wifi Networks' option, which should show the connection after several seconds. I'd accept a PR to add the option to list saved Wifi connections, but I feel that would be potentially a very long and busy list, especially for something like dmenu.

Leaving open for other comments.

**Comment by zzzdeb** [comment]
Option sounds good. I created one pull request. 
For me, the list of saved connection is not that long (under 100). dmenu even rofi seems to be able to handle it easily.

**Comment by firecat53** [comment]
Closed by #74
