### ISSUE TITLE
[FR] Change character marking default connection

### ISSUE THREAD

**Issue by edgar-vincent** [firecat53/networkmanager-dmenu#80]
Hello,

Currently, '==' is used to show which connection is active. I don't know what the general opinion on this is, but I don't find it very appealing. I suggest using something like ∙ (U+2219) instead.

https://github.com/firecat53/networkmanager-dmenu/blob/96ea65073707fcb43c09f86412851bf084b84b10/networkmanager_dmenu#L424

Thanks for your work.

**Comment by firecat53** [comment]
This was intentional to make the active connection easier to find when using dmenu. A quick type of '=' will instantly select the active network (#68). If you are using Rofi, you can use the option `rofi_highlight = True` in your config.ini to visually highlight the active connection instead of marking with `==`. 

I guess this could be made configurable, but I'm not sure it's really worth the extra code. PR's welcome if you're interested!

**Comment by edgar-vincent** [comment]
This makes sense. I thought of making a PR (with my almost non-existent Python skills) for making it configurable, but I agree with you about the fact that it might not be worth it. I'm closing this for now. Thanks!
